//
//  MapModels.swift
//  RSR
//
//  Created by Ehsan on 06/03/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit
import CoreLocation

enum MapModels {
    
    enum AskForPermission {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    
    enum LocateTheUser {
        struct Request {
            
        }
        
        struct Response {
            let stringLocation: String
            let coordinate: CLLocationCoordinate2D
        }
        
        struct ViewModel {
            let stringLocation: String
            let coordinate: CLLocationCoordinate2D
        }
    }
    
}
