//
//  MapPresenter.swift
//  RSR
//
//  Created by Ehsan on 06/03/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol MapPresentable {
    func presentAddress(response: MapModels.LocateTheUser.Response)
}

class MapPresenter: MapPresentable {
    weak var viewController: MapDisplayable?
  
    init(viewController: MapDisplayable) {
        self.viewController = viewController
    }
    
    
    func presentAddress(response: MapModels.LocateTheUser.Response) {
        let viewModel = MapModels.LocateTheUser.ViewModel(stringLocation: response.stringLocation, coordinate: response.coordinate)
        viewController?.displayCustomPin(viewModel: viewModel)
    }
    
}
