//
//  MainViewController.swift
//  RSR
//
//  Created by Ehsan on 05/03/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol MainDisplayable: class {
//    func displaySomething(viewModel: MainModels.ViewModel)
    // func to display error can be added here
}

class MainViewController: UIViewController, MainDisplayable {
//    lazy var interactor: MainBusinessLogic
//    lazy var router: MainRoutable
//    var viewModel: MainModels.ViewModel?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        //doSomething()
    }
    
    // MARK: Do something
    
//    func doSomething() {
//        let request = Main.Something.Request()
//        interactor?.doSomething(request: request)
//    }
//
//    func displaySomething(viewModel: MainModels.ViewModel) {
//        //nameTextField.text = viewModel.name
//    }
}
