//
//  MainInteractor.swift
//  RSR
//
//  Created by Ehsan on 05/03/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
//    func doSomething(request: Main.Something.Request)
}

protocol MainDataStore {
  //var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
  var presenter: MainPresentable?
  //var worker: MainWorker?
  //var name: String = ""
  
    init(presenter: MainPresentable) {
        self.presenter = presenter
    }
    
    
  // MARK: Do something
  
//    func doSomething(request: MainModels.Request) {
//        worker = MainWorker()
//        worker?.doSomeWork()
//
//        let response = MainModels.Response()
//        presenter?.presentSomething(response: response)
//    }
}
